server:
  port: 8086

spring:
  codec:
    max-in-memory-size: 16MB
  application:
    name: file-service
  data:
    mongodb:
      uri: mongodb://files:filesapppass@localhost:27017/files?authSource=files
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8085/api/auth/keys/jwks.json"

minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: miniopass
  bucket: user-files
  create-bucket-if-not-exists: true

spring.servlet.multipart:
  max-file-size: 50MB
  max-request-size: 50MB

ingestservice:
  base-url: http://localhost:8081

n8n:
  baseUrl: https://n8n.easy-ai.it/webhook/e9e561c2-cbce-42b4-9270-c4e3c0cbec17
  username: admin
  password: quickSteps89