server:
  port: 8086

spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: mongodb://files:filesapppass@localhost:27017/files?authSource=files

minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: miniopass
  bucket: user-files
  create-bucket-if-not-exists: true

spring.servlet.multipart:
  max-file-size: 50MB
  max-request-size: 50MB

ingestservice:
  base-url: http://localhost:8081